In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.shape
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [4]:
credits.shape

(4803, 4)

In [5]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [6]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [7]:
movies = movies.merge(credits, left_on="id", right_on="movie_id")

In [8]:
movies.shape

(4803, 24)

In [9]:
movies.rename(columns={'original_title' : 'title'}, inplace=True)
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

### Columns to be retained in the dataset : 
 genres <br>
 movie_id <br>
 keywords <br>
 title <br>
 overview <br>
 popularity <br>
 tagline <br>
 cast <br>
 crew <br>

In [10]:
movies=movies[['movie_id', 'title','genres', 'keywords', 'overview', 'tagline', 'cast', 'crew']]

In [11]:
movies.columns

Index(['movie_id', 'title', 'genres', 'keywords', 'overview', 'tagline',
       'cast', 'crew'],
      dtype='object')

In [12]:
movies.head(1)

movie_id   title                                             genres  \
0     19995  Avatar  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                       tagline  \
0  Enter the World of Pandora.   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [13]:
print(movies['genres'][0])

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]


In [14]:
print(type(movies['genres'][0]))

<class 'str'>


In [15]:
movies.dropna(inplace=True)

In [16]:
import ast

In [17]:
def convert(text) :
    L = []
    for i in ast.literal_eval(text) :
        L.append(i['name'])
    return L

In [18]:
movies['genres'] = movies['genres'].apply(convert)

In [19]:
movies['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)
movies['keywords'][0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [21]:
def convert_top_3(text) :
    counter = 0
    L = []
    for i in ast.literal_eval(text) :
        if(counter<3) :
            L.append(i['name'])
        counter=counter+1
    return L


In [22]:
movies['cast'] = movies['cast'].apply(convert_top_3)
movies['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [23]:
def fetch_director(text) :
    L = []
    for i in ast.literal_eval(text) :
        if i['job'] == 'Director' :
            L.append(i['name'])
    return L

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies['crew'][345]

['Brett Ratner']

In [25]:
movies['overview'] = movies['overview'].apply(lambda x : x.split())
movies['tagline'] = movies['tagline'].apply(lambda x : x.split())
movies.sample(1)

movie_id                     title                       genres  \
4787     86304  All Superheroes Must Die  [Science Fiction, Thriller]   

         keywords                                           overview  \
4787  [superhero]  [Masked, vigilantes, Charge, (Jason, Trost),, ...   

                         tagline                                    cast  \
4787  [May, The, Best, Man, Win]  [Jason Trost, Lucas Till, James Remar]   

               crew  
4787  [Jason Trost]

In [26]:
def collapse_space(L) :
    L1 = []
    for i in L :
        L1.append(i.replace(" ", ""))
    return L1

In [27]:
movies['genres'] = movies['genres'].apply(collapse_space)
movies['keywords'] = movies['keywords'].apply(collapse_space)
movies['cast'] = movies['cast'].apply(collapse_space)
movies['crew'] = movies['crew'].apply(collapse_space)

In [28]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                             tagline  \
0                  [Enter, the, World, of, Pandora.]   
1  [At, the, end, of, the, world,, the, adventure...   
2                        [A, Plan, No, One, Escapes]   
3                                [The, Legend, Ends]   
4       [Lost, in, our, world,, found, in, another.]   

                                            cast                crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]      [JamesCameron]  
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]     [GoreVerbinski]  
2      [DanielCraig, ChristophWaltz, LéaSeydoux]         [SamMendes]  
3      [ChristianBale, MichaelCaine, GaryOldman]  [ChristopherNolan]  
4    [TaylorKitsch, LynnCollins, SamanthaMorton]     [AndrewStanton]

In [29]:
movies['tags'] = movies['overview'] + movies['genres'] +movies['tagline'] +movies['cast']+movies['crew']+movies['keywords']

In [30]:
new_movies = movies.drop(columns = ['overview', 'cast', 'crew', 'keywords', 'tagline', 'genres'])

In [31]:
new_movies['tags'] = new_movies['tags'].apply(lambda x:" ".join(x))
new_movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words="english")

In [33]:
vector = cv.fit_transform(new_movies['tags']).toarray()

In [34]:
vector.shape

(3959, 5000)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vector)

In [37]:
similarity.shape

(3959, 3959)

In [38]:
new_movies.head(1)

movie_id   title                                               tags
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...

In [39]:
new_movies[new_movies['title']=='The Lego Movie'].index[0]

744

In [40]:
print(similarity)

[[1.         0.12369267 0.05309319 ... 0.02002404 0.0325128  0.02411214]
 [0.12369267 1.         0.08471737 ... 0.04260143 0.         0.02564946]
 [0.05309319 0.08471737 1.         ... 0.04571503 0.         0.        ]
 ...
 [0.02002404 0.04260143 0.04571503 ... 1.         0.         0.02076137]
 [0.0325128  0.         0.         ... 0.         1.         0.03370999]
 [0.02411214 0.02564946 0.         ... 0.02076137 0.03370999 1.        ]]


In [41]:
def recommend(movie_title) :
    index = new_movies[new_movies['title']==movie_title].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x:x[1])
    for i in distances[1:10] :
        print(new_movies.iloc[i[0]].title)


In [42]:
recommend('Avatar')

Titan A.E.
Battle: Los Angeles
Star Trek Into Darkness
Aliens vs Predator: Requiem
The Fifth Element
Small Soldiers
The 5th Wave
Independence Day
Predators


In [43]:
recommend('Fantastic Four')

Allegiant
Mad Max Beyond Thunderdome
Divergent
The Hunger Games: Mockingjay - Part 1
Alice Through the Looking Glass
The Covenant
Green Lantern
Containment
The Host


In [44]:
import pickle

In [45]:
pickle.dump(new_movies, open('movies.pkl', 'wb'))
new_movies['title'].values


array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'El Mariachi', 'Newlyweds', 'Shanghai Calling'], dtype=object)

In [46]:
pickle.dump(new_movies.to_dict(), open('movie_dict.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))